"""update recipient model

Revision ID: 315a32c14367
Revises: b7ecb30723ce
Create Date: 2024-07-06 18:05:21.065181

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '315a32c14367'
down_revision: Union[str, None] = 'b7ecb30723ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipeints', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('recipeints', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('recipeints', 'phone_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipeints', 'phone_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('recipeints', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('recipeints', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
