"""create role table

Revision ID: 653a8ee01a13
Revises: 8590309a8981
Create Date: 2024-06-30 17:05:18.316745

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "653a8ee01a13"
down_revision: Union[str, None] = "8590309a8981"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("role_uid", sqlmodel.sql.sqltypes.GUID(), nullable=True)
    )
    op.create_foreign_key(None, "users", "roles", ["role_uid"], ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "role_uid")
    # ### end Alembic commands ###
