"""update role

Revision ID: 8590309a8981
Revises: 3c21d0bac2e7
Create Date: 2024-06-30 16:31:49.247903

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8590309a8981"
down_revision: Union[str, None] = "3c21d0bac2e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles",
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    )
    op.create_unique_constraint(None, "roles", ["role"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "roles", type_="unique")
    op.drop_column("roles", "role")
    # ### end Alembic commands ###
