"""add recipient model

Revision ID: b7ecb30723ce
Revises: e9faa07ceb19
Create Date: 2024-07-06 13:46:11.101819

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7ecb30723ce"
down_revision: Union[str, None] = "e9faa07ceb19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipeints",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column(
            "first_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "last_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "phone_number", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(op.f("ix_recipeints_uid"), "recipeints", ["uid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recipeints_uid"), table_name="recipeints")
    op.drop_table("recipeints")
    # ### end Alembic commands ###
