"""user initial migration

Revision ID: f802cc74cf76
Revises: 
Create Date: 2024-06-29 10:12:15.185539

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f802cc74cf76"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "first_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "last_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
    )
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "username", sa.VARCHAR(length=150), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
